server:
  port: 80
#数据库连接
spring:
  application:
    name: reggie-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: llh105406
    url: jdbc:mysql://localhost:3306/reggie_test
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #开启实体类对象包扫描
  type-aliases-package: org.example.reggie.domain.po
  #开启通用枚举
  type-enums-package:
  configuration:
    #开启驼峰结构
    map-underscore-to-camel-case: true
    #更加详细的mybatis-plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

#设置图片存储路径
reggie:
  path: D:/javaProject/SpringBoot项目/reggie-app/src/main/resources/backend/images/menus/

